<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\LmuOverlay.Contracts\LmuOverlay.Contracts.csproj" />
    <ProjectReference Include="..\LmuOverlay.Domain\LmuOverlay.Domain.csproj" />
  </ItemGroup>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
      <_Parameter1>LmuOverlay.Core.Tests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>
</Project>
