namespace LmuOverlay.LmuSharedMemory;

public static class LmuApiLayoutV1
{
    public const string MapName = "LMU_Data";
    public const string EventName = "LMU_Data_Event";
    public const int MaximumVehicles = 104;
    public const int ObjectSize = 324_820;

    public const int EventCount = 16;
    public const int EventSize = sizeof(uint);
    public const int ScoringUpdateEventIndex = 10;
    public const int TelemetryUpdateEventIndex = 11;

    public const int GameVersionOffset = 64;
    public const int GameVersionLength = 4;

    public const int ScoringOffset = 1_632;
    public const int TrackNameOffset = ScoringOffset;
    public const int TrackNameLength = 64;
    public const int SessionCodeOffset = ScoringOffset + 64;
    public const int SessionCurrentElapsedTimeOffset = ScoringOffset + 68;
    public const int SessionEndElapsedTimeOffset = ScoringOffset + 76;
    public const int SessionMaximumLapsOffset = ScoringOffset + 84;
    public const int SessionLapLengthOffset = ScoringOffset + 88;
    public const int ScoredVehiclesOffset = ScoringOffset + 104;
    public const int GamePhaseOffset = ScoringOffset + 108;
    public const int YellowFlagStateOffset = ScoringOffset + 109;
    public const int SectorFlagsOffset = ScoringOffset + 110;
    public const int IsRealtimeOffset = ScoringOffset + 115;
    public const int PlayerNameOffset = ScoringOffset + 116;
    public const int PlayerNameLength = 32;
    public const int CloudinessOffset = ScoringOffset + 212;
    public const int RainIntensityOffset = ScoringOffset + 220;
    public const int AmbientTemperatureOffset = ScoringOffset + 228;
    public const int TrackTemperatureOffset = ScoringOffset + 236;
    public const int WindOffset = ScoringOffset + 244;
    public const int MinimumPathWetnessOffset = ScoringOffset + 268;
    public const int MaximumPathWetnessOffset = ScoringOffset + 276;
    public const int AveragePathWetnessOffset = ScoringOffset + 332;
    public const int TrackGripLevelOffset = ScoringOffset + 349;
    public const int CloudCoverageOffset = ScoringOffset + 350;
    public const int VehicleScoringArrayOffset = ScoringOffset + 560;
    public const int VehicleScoringSize = 584;

    public const int ScoringVehicleIdOffset = 0;
    public const int ScoringDriverNameOffset = 4;
    public const int ScoringDriverNameLength = 32;
    public const int ScoringVehicleNameOffset = 36;
    public const int ScoringVehicleNameLength = 64;
    public const int ScoringCompletedLapsOffset = 100;
    public const int ScoringSectorOffset = 102;
    public const int ScoringLapDistanceOffset = 104;
    public const int ScoringBestSector1Offset = 128;
    public const int ScoringBestSector2Offset = 136;
    public const int ScoringBestLapTimeOffset = 144;
    public const int ScoringLastSector1Offset = 152;
    public const int ScoringLastSector2Offset = 160;
    public const int ScoringLastLapTimeOffset = 168;
    public const int ScoringCurrentSector1Offset = 176;
    public const int ScoringCurrentSector2Offset = 184;
    public const int ScoringPitStopsOffset = 192;
    public const int ScoringPenaltiesOffset = 194;
    public const int VehicleScoringIsPlayerOffset = 196;
    public const int ScoringInPitsOffset = 198;
    public const int ScoringPositionOffset = 199;
    public const int ScoringVehicleClassOffset = 200;
    public const int ScoringVehicleClassLength = 32;
    public const int ScoringGapToNextOffset = 232;
    public const int ScoringLapsBehindNextOffset = 240;
    public const int ScoringGapToLeaderOffset = 244;
    public const int ScoringLapsBehindLeaderOffset = 252;
    public const int ScoringLapStartElapsedTimeOffset = 256;
    public const int ScoringPitStateOffset = 457;
    public const int ScoringFlagOffset = 504;
    public const int ScoringUnderYellowOffset = 505;
    public const int ScoringInGarageOffset = 507;
    public const int ScoringFuelFractionOffset = 578;
    public const int ScoringDrsActiveOffset = 579;

    public const int TelemetryOffset = 128_464;
    public const int ActiveVehiclesOffset = TelemetryOffset;
    public const int PlayerVehicleIndexOffset = TelemetryOffset + 1;
    public const int PlayerHasVehicleOffset = TelemetryOffset + 2;
    public const int VehicleTelemetryArrayOffset = TelemetryOffset + 4;
    public const int VehicleTelemetrySize = 1_888;
    public const int VehicleNameOffset = 32;
    public const int VehicleNameLength = 64;
    public const int TelemetryVehicleIdOffset = 0;
    public const int TelemetryElapsedTimeOffset = 12;
    public const int TelemetryLapNumberOffset = 20;
    public const int TelemetryLapStartElapsedTimeOffset = 24;
    public const int TelemetryLocalVelocityOffset = 184;
    public const int TelemetryLocalAccelerationOffset = 208;
    public const int TelemetryGearOffset = 352;
    public const int TelemetryEngineRpmOffset = 356;
    public const int TelemetryEngineWaterTemperatureOffset = 364;
    public const int TelemetryEngineOilTemperatureOffset = 372;
    public const int TelemetryThrottleOffset = 388;
    public const int TelemetryBrakeOffset = 396;
    public const int TelemetrySteeringOffset = 404;
    public const int TelemetryClutchOffset = 412;
    public const int TelemetryFuelOffset = 524;
    public const int TelemetryEngineMaximumRpmOffset = 532;
    public const int TelemetryScheduledStopsOffset = 540;
    public const int TelemetryOverheatingOffset = 541;
    public const int TelemetryBodyDetachedOffset = 542;
    public const int TelemetryDentSeverityOffset = 544;
    public const int TelemetryDentSeverityCount = 8;
    public const int TelemetryLastImpactElapsedTimeOffset = 552;
    public const int TelemetryLastImpactMagnitudeOffset = 560;
    public const int TelemetryCurrentSectorOffset = 600;
    public const int TelemetryMaximumGearsOffset = 605;
    public const int TelemetryFrontTireCompoundIndexOffset = 606;
    public const int TelemetryRearTireCompoundIndexOffset = 607;
    public const int TelemetryFuelCapacityOffset = 608;
    public const int TelemetryFrontTireCompoundNameOffset = 620;
    public const int TelemetryRearTireCompoundNameOffset = 638;
    public const int TelemetryTireCompoundNameLength = 18;
    public const int TelemetryRearBrakeBiasOffset = 664;
    public const int TelemetryDeltaBestOffset = 696;
    public const int TelemetryBatteryChargeOffset = 704;
    public const int TelemetryLapInvalidatedOffset = 745;
    public const int TelemetryAbsActiveOffset = 746;
    public const int TelemetryTractionControlActiveOffset = 747;
    public const int TelemetrySpeedLimiterActiveOffset = 748;
    public const int TelemetryTractionControlLevelOffset = 750;
    public const int TelemetryTractionControlMaximumOffset = 751;
    public const int TelemetryTractionControlSlipLevelOffset = 752;
    public const int TelemetryTractionControlSlipMaximumOffset = 753;
    public const int TelemetryTractionControlCutLevelOffset = 754;
    public const int TelemetryTractionControlCutMaximumOffset = 755;
    public const int TelemetryAbsLevelOffset = 756;
    public const int TelemetryAbsMaximumOffset = 757;
    public const int TelemetryRegenerationOffset = 768;
    public const int TelemetryStateOfChargeOffset = 772;
    public const int TelemetryVirtualEnergyOffset = 776;
    public const int TelemetryGapToCarAheadOffset = 780;
    public const int TelemetryGapToCarBehindOffset = 784;
    public const int TelemetryVehicleModelOffset = 796;
    public const int TelemetryVehicleModelLength = 30;
    public const int TelemetryVehicleClassOffset = 826;
    public const int TelemetryWheelArrayOffset = 848;
    public const int TelemetryWheelSize = 260;
    public const int TelemetryWheelWearOffset = 152;
    public const int TelemetryWheelFlatOffset = 177;
    public const int TelemetryWheelDetachedOffset = 178;
    public const int TelemetryWheelCarcassTemperatureOffset = 204;

    public static int EventOffset(int eventIndex) => eventIndex * EventSize;

    public static int VehicleTelemetryOffset(int vehicleIndex) =>
        VehicleTelemetryArrayOffset + (vehicleIndex * VehicleTelemetrySize);

    public static int VehicleScoringOffset(int vehicleIndex) =>
        VehicleScoringArrayOffset + (vehicleIndex * VehicleScoringSize);
}
